version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: image-uploader-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: image_uploader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - image_uploader_postgres_data:/var/lib/postgresql/data

volumes:
  image_uploader_postgres_data: